### ISSUE TITLE
EL6 support

### ISSUE THREAD

**Issue by martbhell** [jeffwidman/ansible-yum-cron#1]
Hi, 

I'm planning to start using this role and it looks nice, thanks!

Btw, EL6 will not work because it's only configured in /etc/sysconfig/yum-cron and the config file looks completely different.

Here's another role which shows how it's done on EL6: https://github.com/kaffeeh/ansible-yum-cron

**Comment by jeffwidman** [comment]
You're welcome, glad you like it. 

Unfortunately, I don't have time/interest adding EL6 as all my current boxes use EL7/CentOS 7 and as time goes on EL6 will gradually become less common. 

Normally I'd be very open to merging a PR adding support if you wanted to put one together, but in this case I'm hesitant. As you point out, the config location/variables are completely different. It's not just a few changes, it's almost a completely different package.

Unless there's some reason I'm missing why you need support for both in a single role, I suggest using this role for your EL7 boxes, and the other role you linked to for your EL6 boxes. If I'm misunderstanding something, feel free to reopen.
