### ISSUE TITLE
rectify the defaults file

### ISSUE THREAD

**Issue by rajhotagit19** [jeffwidman/ansible-yum-cron#14]
There is a variable mentioned [here](https://github.com/jeffwidman/ansible-yum-cron/blob/ec4fa101a5147f7fc0ecb3b7973bce75c0a26870/defaults/main.yml#L27) wrongly.

Should not this be as following as we read in README.

yum_cron_daily_base_options: "{{ yum_cron_hourly_base_options }}"

Thanks in advance.

Regards,
Pravanjan Hota

**Comment by rajhotagit19** [comment]
If we do not fix the same, it fails to run the playbook.

<pre>
[]$ ansible-playbook -i ./tttt --limit="XX.XX.XX.XX" --become-user root -u root .ansible/yum.yml --check --diff

PLAY [Test yum-cron] ************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************
ok: [XX.XX.XX.XX]

TASK [yum-cron : Ensures cron(ie) installed] ************************************************************************************************************************************************
ok: [XX.XX.XX.XX]

TASK [yum-cron : Ensures cron(ie) service is running] ***************************************************************************************************************************************
ok: [XX.XX.XX.XX]

TASK [Ensures yum-cron installed] ***********************************************************************************************************************************************************
ok: [XX.XX.XX.XX]

TASK [Configure yum-cron.conf] **************************************************************************************************************************************************************
fatal: [XX.XX.XX.XX]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: {{ hourly_base_options }}: 'hourly_base_options' is undefined"}

PLAY RECAP **********************************************************************************************************************************************************************************
XX.XX.XX.XX            : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

[]$
</pre>

**Comment by jeffwidman** [comment]
Yes, good catch. @rajhotagit19 Want to submit a PR fixing it?

**Comment by rajhotagit19** [comment]
> Yes, good catch. @rajhotagit19 Want to submit a PR fixing it?
https://github.com/jeffwidman/ansible-yum-cron/pull/15
